# -*- coding: utf-8 -*-
{
    'name': 'CristO',
    'version': '13.2.0',
    'category': '',
    'sequence': 2,
    'summary': 'Parish & Religious Management Software',
    'description': """Parish & Religious Management Software""",
    'author': 'Boscosoft Technologies Pvt Ltd',
    'website': 'https://www.boscosofttech.com',
    'depends': [
                'base','mail','web','export_xlsx','report_xlsx','custom_filters'
               ],
    'data': [
                'security/cristo_security.xml',
                'security/cristo_roles_security.xml',
                'security/ir.model.access.csv',
                
                'data/res.country.state.csv',
                'data/personal_data.xml',
                'data/ecclesial_data.xml',
                'data/educational_data.xml',
                'data/religious_data.xml',
                'data/study_level_member.xml',
                'data/res_partner_data.xml',
                'data/member_renewal_cron.xml',
                'data/member_renewal_email_template.xml',
                'data/house_member_date_cron.xml',
                'data/house_member_date_email_template.xml',
                'data/cron_activity.xml',
                
                
                'wizard/report/wizard_confreres.xml',
                'wizard/report/wizard_anniversary.xml',
                'wizard/report/wizard_family_statistics.xml',
                'wizard/update/update_province_statistics.xml',
                'wizard/report/sacraments/wizard_marriage_view.xml',
                'wizard/report/wizard_family_list.xml',
                'wizard/report/wizard_family_census.xml',
                'wizard/report/wizard_member_profile.xml',
#                 'wizard/report/wizard_eccparish_all_anniversary.xml',
                
                
                'views/res_ecclesia_views.xml',
                'views/res_member_views.xml',
                'views/res_family_views.xml',
                'views/res_configuration_view.xml',
                'views/res_religious_views.xml',
                'views/res_partner_views.xml',
                'views/res_sacraments_views.xml',
                'views/res_membership_views.xml',
                'views/res_users_views.xml',
                'views/res_config_settings_views.xml',
                'views/report/confreres_template.xml',
                'views/report/confreres.xml',
                'views/report/anniversary_template.xml',
                'views/report/anniversary.xml',
                'views/report/family_statistics_template.xml',
                'views/report/family_statistics.xml',
                'views/report/baptism_template.xml',
                'views/report/baptism.xml',
                'views/report/family_card_template.xml',
                'views/report/family_card.xml',
                'views/report/first_holy_communion_template.xml',
                'views/report/first_holy_communion.xml',
                'views/report/confirmation_template.xml',
                'views/report/confirmation.xml',
                'views/report/death_template.xml',
                'views/report/death.xml',
                'views/report/family_list_template.xml',
                'views/report/family_list.xml',
                'views/report/family_census_template.xml',
                'views/report/family_census.xml',
                'views/ir_model_views.xml',
                'views/menus.xml',
                'views/cristo_report/cristo_report.xml',
                'views/ecc_parish_profile/report_ecc_parish_profile.xml',
                'views/member_profile/report_member_profile.xml',
                'views/rel_province_profile/report_rel_province_profile.xml',
                'views/rel_community_profile/report_rel_community_profile.xml',
                'views/rel_institution_profile/report_rel_institution_profile.xml',
                'views/ecc_diocese_profile/report_ecc_diocese_profile.xml',
                'views/report/report_marriage.xml',
                'views/report/xlsx_report.xml',
                'views/report/sacraments/marriage_template.xml',
                'views/report/sacraments/sacraments_report.xml',
#                 'views/report/ecclesia_all_anniversary_wizard.xml',
            ],
    'qweb': ['static/src/xml/systray.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
